services:

  # =========================
  # SQL Server
  # =========================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Proposta123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - seguros-network

  # =========================
  # RabbitMQ
  # =========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - seguros-network

  # =========================
  # PropostaService API
  # =========================
  propostaservice:
    build:
      context: ./PropostaService.Api/..
      dockerfile: ./PropostaService.Api/Dockerfile
    container_name: propostaservice
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PropostasDb;User Id=sa;Password=Proposta123!;TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__Port: "5672"
      RabbitMQ__QueueName: "propostas-criadas"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - sqlserver
      - rabbitmq
    ports:
      - "5000:80"
    networks:
      - seguros-network

  # =========================
  # ContratacaoService Worker
  # =========================
  contratacao-worker:
    build:
      context: ./ContratacaoService.Worker/..
      dockerfile: ./ContratacaoService.Worker/Dockerfile
    container_name: contratacao-worker
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ContratacoesDb;User Id=sa;Password=Proposta123!;TrustServerCertificate=True;"
      RabbitMQ__HostName: "rabbitmq"
      RabbitMQ__UserName: "guest"
      RabbitMQ__Password: "guest"
      RabbitMQ__Port: "5672"
      RabbitMQ__QueueName: "propostas-criadas"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - seguros-network

  # =========================
  # ContratacaoService API
  # =========================
  contratacao-api:
    build:
      context: ./ContratacaoService.Api/..
      dockerfile: ./ContratacaoService.Api/Dockerfile
    container_name: contratacao-api
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ContratacoesDb;User Id=sa;Password=Proposta123!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - contratacao-worker
    ports:
      - "5001:80"
    networks:
      - seguros-network

volumes:
  sqlserver-data:

networks:
  seguros-network:
    driver: bridge
